### ISSUE TITLE
napalm_ping error when source is not specified

### ISSUE THREAD

**Issue by ThreeFDDI** [nornir-automation/nornir#555] opened 2020-05-26 23:14 UTC
When using the napalm_ping plugin without a source explicitly defined the following error occurs:

2020-05-25 19:04:04 DEBUG    write_channel: b'ping 10.10.23.2 timeout 2 size 100 repeat 5 source None\n'
2020-05-25 19:04:04 DEBUG    read_channel:
2020-05-25 19:04:04 DEBUG    read_channel: ping 10.10.23.2 timeout 2 size 100 repeat 5 source None
                                                          ^
% Invalid input detected at '^' marker.

**Comment by ktbyers** [comment] 2020-05-27 04:01
This caused by us setting source=None in the argument list (instead of the default of source="") which NAPALM uses.

@ThreeFDDI and I were looking at this today.

**Comment by ktbyers** [comment] 2020-05-27 04:04
Should be fixed now.

**Closed by ktbyers** 2020-05-27 04:04 UTC

**Comment by dbarrosop** [comment] 2020-05-27 06:45
if this PR isn't opened in nornir-automation/nornir-napalm the change will be lost after nornir3 is released

**Comment by ktbyers** [comment] 2020-05-27 15:17
Corresponding PR in nornir_napalm is here (for reference):

https://github.com/nornir-automation/nornir_napalm/pull/5
