### ISSUE TITLE
use plugin after, how to write Cisco's enable password

### ISSUE THREAD

**Issue by shijinlong12** [nornir-automation/nornir#827] opened 2022-10-20 07:08 UTC
Sorry, my english is not good

my used nornir and relevant plugins version is
![image](https://user-images.githubusercontent.com/40626840/196871618-41bb9770-3cad-4552-bac0-eb1a6e894992.png)

I now encounter a problem,

As you can see, i used a **nornir_table_inventory** plugin to processed my host data. It works.
![image](https://user-images.githubusercontent.com/40626840/196877625-4364f5ef-6ca4-4b0b-a3da-e0992d9f61ae.png)
![image](https://user-images.githubusercontent.com/40626840/196875412-26b41ea4-b7cc-4167-b77e-ec3ac36a0cc9.png)

but when using **napalm_get** to get **get_facts**, appear **Please ensure you pass the 'secret' argument to ConnectHandler.** error
![image](https://user-images.githubusercontent.com/40626840/196875901-2bb437f4-7cc9-41b4-b383-9ef2ee5d4a52.png)

the picture is detailed host data below, the plugin address is **https://github.com/jiujing/nornir_table_inventory**
![image](https://user-images.githubusercontent.com/40626840/196875845-8749fb8b-0bd2-45d6-b96f-88f2183edbc4.png)

I checked all the questions containing this error, but no one is in the same situation as me so.

A better answer would be to ask the plug-in author, but the plug-in author has not replied to me, so let's ask 

How should I fill in the secret

napalm_options: {'secret': 'my_secret_pass'} is Already tried

thank you very much

**Comment by jiujing** [comment] 2022-10-24 07:43
nornir_table_inventory  does support netmiko only. It does not  support napalm.
Maybe It will support in the future.I will upgrade some functions .

**Comment by shijinlong12** [comment] 2022-10-24 07:45
> nornir_table_inventory does support netmiko only. It does not support napalm. Maybe It will support in the future.I will upgrade some functions .

OK的 家人 已经用ntpalm实现功能了 感谢

**Comment by kashyappatel1988** [comment] 2022-10-24 08:03
@jiujing I test this code and it ran perfectly fine 


```

def get_nornir_by_your_func(some_args=None, num_workers=100):
  """Use any way to get some data(such as sql or restful api), and transform them into form as follwing"""
  data = [{'name': 'test1', 'hostname': 'xxxx',
           'platform': 'junos', 'port': 22, 'username': 'xxxx',
           'password': 'xxx', 'city': 'bj'},
          ]
  runner = {
      "plugin": "threaded",
      "options": {
          "num_workers": num_workers,
      },
  }
  inventory = {
      "plugin": "FlatDataInventory",
      "options": {
          "data": data,
      },
  }
  nr = InitNornir(runner=runner, inventory=inventory)
  return nr


if __name__ == '__main__':
  
  nr = get_nornir_by_your_func()
  bj_devs = nr.filter(city='bj')
  r = bj_devs.run(task=napalm_get, getters=['facts'])
  print_result(r)
```

**Comment by jiujing** [comment] 2022-10-24 10:57
> @jiujing You may already have it , I tested below code and it ran perfectly fine
> 
> ```
> 
> def get_nornir_by_your_func(some_args=None, num_workers=100):
>   """Use any way to get some data(such as sql or restful api), and transform them into form as follwing"""
>   data = [{'name': 'test1', 'hostname': 'xxxx',
>            'platform': 'junos', 'port': 22, 'username': 'xxxx',
>            'password': 'xxx', 'city': 'bj'},
>           ]
>   runner = {
>       "plugin": "threaded",
>       "options": {
>           "num_workers": num_workers,
>       },
>   }
>   inventory = {
>       "plugin": "FlatDataInventory",
>       "options": {
>           "data": data,
>       },
>   }
>   nr = InitNornir(runner=runner, inventory=inventory)
>   return nr
> 
> 
> if __name__ == '__main__':
>   
>   nr = get_nornir_by_your_func()
>   bj_devs = nr.filter(city='bj')
>   r = bj_devs.run(task=napalm_get, getters=['facts'])
>   print_result(r)
> ```

It does work, if you do not want some connection options such as enable password . I did not support napalm especially. Some common arguments are same，such as username or password，So it does work ,when you use nornir_table_inventory with no sepical arguments.But some arguments are especial such as Connection Arguments Options. Nornir-table-inventory can parse data with "netmiko_" prefix to netmiko connection options.

**Comment by dbarrosop** [comment] 2022-10-24 14:14
I am closing this issue as I don't think this is related to nornir itself. Otherwise, feel free to reopen. If the issue is related to a plugin, it might be worth moving the conversation there.

Thanks!

**Closed by dbarrosop** 2022-10-24 14:14 UTC
