### ISSUE TITLE
Hosts added to inventory using add_host() not inheriting group attributes

### ISSUE THREAD

**Issue by jrdwsn** [nornir-automation/nornir#419] opened 2019-08-05 14:35 UTC
Hosts imported into the Inventory from CSV file (using the `add_host()` function) are not inheriting groups attributes.

Using the following function for basic import:

```python
def import_device_csv(norn, filename):
    """Imports devices from a CSV file into the Nornir inventory"""
    with open(filename) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["protocol"] == "ssh":
                groups = ["cisco_ios"]
            elif row["protocol"] == "telnet":
                groups = ["cisco_ios_telnet"]
            norn.inventory.add_host(
                name=row["name"],
                hostname=row["ip_addr"],
                groups=groups
            )
```

As a test, I'm defining one host in the `hosts.yaml` file, and the other in `devices.csv` file:

```yaml
---
# hosts.yml file

device1:
    hostname: 1.2.3.4
    groups:
        - cisco_ios_telnet
```

```yaml
---
# groups.yaml file
cisco_ios:
    platform: ios

cisco_ios_telnet:
    platform: ios
    connection_options:
        netmiko:
            extras:
                device_type: cisco_ios_telnet
        napalm:
            extras:
                optional_args:
                    transport: telnet
```

The CSV for import:

```
name,ip_addr,protocol
device2,5.6.7.8,telnet
```

Initialising the inventory then importing hosts from the CSV:

```python
def main():

    nr = InitNornir(config_file="config.yaml")

    # Import CSV and populate inventory
    import_device_csv(nr, "devices.csv")

    import ipdb; ipdb.set_trace()
    ...
```

From the debugger, I can see the correct group is assigned but the inherited keys are not being picked up by CSV imported host `device2`:

```
ipdb> host1 = nr.inventory.hosts["device1"]
ipdb> host2 = nr.inventory.hosts["device2"]
ipdb> host1.groups
['cisco_ios_telnet']
ipdb> host2.groups
['cisco_ios_telnet']
ipdb> host1.platform
'ios'
ipdb> host2.platform
ipdb> 
```

**Comment by dbarrosop** [comment] 2019-08-09 07:03
would you mind sharing a sample csv?

**Comment by jrdwsn** [comment] 2019-08-20 11:27
The `devices.csv` file used in the above example contained the following:

```
name,ip_addr,protocol
device2,5.6.7.8,telnet
```

This was just to demonstrate the issue.

**Comment by kpeterson-sf** [comment] 2020-09-23 19:34
worked for me with 2.5.0 and 2.4.0 with no config.yaml file.


```
ipdb> nr.inventory.hosts['device2'].platform
'ios'
ipdb> nr.inventory.hosts['device2'].data
{}
ipdb> nr.inventory.hosts['device2'].name
'device2'
ipdb> nr.inventory.hosts['device2'].groups
['cisco_ios_telnet']
ipdb> 
```

**Comment by dbarrosop** [comment] 2020-10-04 08:55
I am closing this one because we haven’t been able to reproduce. Also because nornir3 has changed this dramatically (internally) so there is a high chance that if there was an issue it’s been fixed. Feel free to reopen if it’s still an issue with nornir3

**Closed by dbarrosop** 2020-10-04 08:55 UTC
