### ISSUE TITLE
Netmiko missing device_type mapping from Napalm drivers including napalm community drivers

### ISSUE THREAD

**Issue by walidamer711** [nornir-automation/nornir#262] opened 2018-10-24 09:11 UTC
I find a missing mapping as per the below from netmiko connection, there is no mapping for napalm supported driver (nxos_ssh).

nornir/nornir/plugins/connections/netmiko.py 
napalm_to_netmiko_map = {
    "ios": "cisco_ios",
    "nxos": "cisco_nxos",
    "eos": "arista_eos",
    "junos": "juniper_junos",
    "iosxr": "cisco_xr",
}

the supported napalm drivers are:
IOS NXOS EOS JUNOS IOSXR NXOS_SSH

**Comment by dbarrosop** [comment] 2018-10-24 09:17
Would you mind sending a PR?

**Comment by ktbyers** [comment] 2018-10-24 17:15
I could probably go either way on this, but that was by design.

The nxos_ssh is a bit idiosyncratic in napalm (i.e. the combining of platform and transport). I think we possibly shouldn't propagate that pattern into nornir.

You could solve that problem by doing this in inventory:

```
nxos_group:
  connection_options:
    napalm:
      platform: nxos_ssh
    netmiko:
      platform: cisco_nxos
```

Alternatively, a fix to that problem could be made in the napalm connection plugin by detecting port 22 and switching the napalm driver to nxos_ssh.

**Comment by walidamer711** [comment] 2018-10-25 07:09
I am running 2.0 and the below worked fine with me.
nxos_group:
  napalm_options:
    platform: nxos_ssh
  netmiko_options:
    platform: cisco_nxos

I agree that it would be better, if feasible, to let napalm connection handle the dispatching of the transport information so platform would be always (nxos) and transport would be one of the following for example (http, https, ssh).

**Comment by ktbyers** [comment] 2018-10-25 20:10
I am going to broaden this issue a bit...as I think it is relevant (see title change).

**Comment by ktbyers** [comment] 2018-10-25 20:11
The map probably should work for napalm community drivers (at least if they are pretty actively being worked on/maintained).

**Comment by walidamer711** [comment] 2018-10-27 06:45
do we need to keep this mixed approach use "platform" or override with {connection}_options if exists.
in this case I think a separate mapping module could be better, because right now we reference to napalm drivers, so it could handle the mapping between "platform" and all connections plugins, even for future ones. netconf, for example, has its own  device_params types (name= nexus, iosxr, iosxe).

If we remove the use of "platform", we could have the same approach in Ansible that connection_options must be provided whenever it will be used.

**Comment by ktbyers** [comment] 2018-10-27 15:44
I am fine either way...so let's just do the nxos_ssh in the mapper.

**Comment by walidamer711** [comment] 2018-10-27 16:14
Ok I will soon try to send pr. But let me clarify this do I need to follow the contribution guide and create a new branch in order to make this change in the code.

**Comment by ktbyers** [comment] 2018-10-27 16:29
You will need to submit a PR...so this means you will need to create a fork in GitHub and make changes to your fork and then submit a PR from there.

Whether you create a branch in your fork is up to you (but probably better for long-term cleanliness of your own fork).

**Comment by dbarrosop** [comment] 2018-11-09 09:43
Anything to do here or should we close it?

**Comment by walidamer711** [comment] 2018-11-09 12:37
I believe we can close it.

**Comment by dbarrosop** [comment] 2018-11-09 12:42
Ok, closing it.

**Closed by dbarrosop** 2018-11-09 12:42 UTC

**Comment by Kircheneer** [comment] 2020-04-20 14:41
Reviving this as there's a similar problem for fortios/fortinet.

Napalm uses fortios while Netmiko uses fortinet. I see that napalm-fortios is not really actively maintained though. Nevertheless, wouldn't it be useful to have these kind of mappings in Nornir?

**Comment by dmfigol** [comment] 2020-04-20 15:04
@Kircheneer if you really want this change, feel free to submit a PR.
Personally I feel that this mapper in netmiko connection plugin creates more maintenance burden than solves probles.
Alternatively, Kirk suggested above how to solve this:
```
some_group:
  connection_options:
    napalm: napalm-fortios
      platform: 
    netmiko:
      platform: fortinet
```
