### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode' when no hostname specified

### ISSUE THREAD

**Issue by dragosstan2602** [nornir-automation/nornir#550] opened 2020-05-19 12:50 UTC
Hi guys,
I was getting this exception thrown when not explicitly specifying the hostname value under the host in the inventory file.
```
---
vEOS-LSW01:
  groups:
    - tors

vEOS-LSW02:
  groups:
    - tors
```
I assumed it would default to the `host` value if the `hostname` value is not populated going by the docs (which have some hosts defined without `hostname` values).

**Comment by dmfigol** [comment] 2020-07-24 16:34
it's duplicate of #289. Closing this issue. That said it would be nice to have better error message if this happens.

**Closed by dmfigol** 2020-07-24 16:34 UTC
