### ISSUE TITLE
issue adding nornir as a dependency with poetry since 2.1.0 release

### ISSUE THREAD

**Issue by enzzzy** [nornir-automation/nornir#357] opened 2019-03-19 09:41 UTC
Can't add nornir 2.1.0 as a dependency for a project when using poetry. 
```
$ mkdir zzz && cd zzz
$ pyenv local 3.7.2
$ pyenv version
3.7.2 (set by /tmp/zzz/.python-version)
$ poetry init
...snip...
$ cat pyproject.toml
[tool.poetry]
name = "zzz"
version = "0.1.0"
description = ""
authors = ["enzzzy@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
$ poetry add nornir
Creating virtualenv zzz-py3.7 in /Users/enzzzy/Library/Caches/pypoetry/virtualenvs
Using version ^2.1 for nornir

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project must support the following Python versions: ^3.7
Because no versions of nornir match >2.1,<3.0
 and nornir (2.1.0) requires Python >=3.6,<3.8, nornir is forbidden.
So, because zzz depends on nornir (^2.1), version solving failed.

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```
Not sure where the issue exactly is, I'm not familiar enough with poetry to troubleshoot this.  I would expect the python version requirement is met since 3.7.2 > 3.6 && 3.7.2 < 3.8.

**Comment by enzzzy** [comment] 2019-03-19 09:59
If I modify the python version constraint in pyproject.toml of my project to:
`python = ">= 3.6, < 3.8"` then it works.
Am I misunderstanding how version constraints work?

**Comment by dbarrosop** [comment] 2019-03-19 10:38
I personally think this is a bug in poetry but as a workaround we will fix nornir to require python ^3.6

**Comment by dbarrosop** [comment] 2019-03-19 10:54
For reference; https://github.com/sdispater/poetry/issues/743

**Comment by dbarrosop** [comment] 2019-03-19 11:07
Could you try specifying the branch `deployment_fixes` in your dependencies and see if the problem goes away? I still think it's a poetry issue but no point in making our users suffer the pain while we discuss it with them

**Comment by enzzzy** [comment] 2019-03-19 13:03
Seems to work and agree!

**Comment by dmfigol** [comment] 2019-03-19 14:16
@enzzzy meanwhile you can specify tilde python requirement in your `pyproject.toml`, e.g. instead change `^3.6` to `~3.6` or `^3.7` to `~3.7`

**Comment by dbarrosop** [comment] 2019-03-19 15:00
no need, just uploaded nornir 2.1.1 to pypi so if you update your dependencies it should be good now. Can you try? I am closing the issue but feel free to reopen if the issue is not fixed.

**Closed by dbarrosop** 2019-03-19 15:00 UTC

**Comment by enzzzy** [comment] 2019-03-19 15:12
Yes; it works with 2.1.1 on pypi.
Thx for the quick reaction & fix!
