### ISSUE TITLE
Installation fails due to conflicting junos-eznc version

### ISSUE THREAD

**Issue by NeolithEra** [nornir-automation/nornir#457] opened 2019-12-11 14:11 UTC
Hi, users are unable to run **_nornir_** due to dependency conflict with _**junos-eznc**_ package. As shown in the following full dependency graph of **_nornir_**, **_napalm_** requires _**junos-eznc ==2.2.1**_，while **_nornir_** requires **_junos-eznc >=2.2,<3.0_**.

According to pip’s _“first found wins”_ installation strategy, _**junos-eznc 2.3.1**_ is the actually installed version. However, _**junos-eznc 2.3.1**_ does not satisfy _**==2.2.1**_.

### Dependency tree-----------
```
nornir - 2.3.0
| +- colorama(install version:0.4.3 version range:>=0.4.1,<0.5.0)
| +- jinja2(install version:2.10.3 version range:>=2,<3)
| | +- markupsafe(install version:1.1.1 version range:>=0.23)
| +- junos-eznc(install version:2.3.1 version range:>=2.2,<3.0)
| +- mypy_extensions(install version:0.4.3 version range:>=0.4.1,<0.5.0)
| +- napalm(install version:2.5.0 version range:>=2,<3)
| | +- cffi(install version:1.13.2 version range:>=1.11.3)
| | +- ciscoconfparse(install version:1.4.11 version range:*)
| | +- future(install version:0.18.2 version range:*)
| | +- jinja2(install version:2.10.3 version range:*)
| | | +- markupsafe(install version:1.1.1 version range:>=0.23)
| | +- junos-eznc(install version:2.2.1 version range:==2.2.1)
| | | +- jinja2(install version:2.10.3 version range:>=2.7.1)
| | | | +- markupsafe(install version:1.1.1 version range:>=0.23)
| | | +- lxml(install version:4.4.2 version range:>=3.2.4)
| | | +- ncclient(install version:0.6.6 version range:>=0.5.4)
| | | | +- lxml(install version:4.4.2 version range:>=3.3.0)
| | | | +- paramiko(install version:2.7.1 version range:>=1.15.0)
| | | | +- selectors2(install version:2.0.1 version range:>=2.0.1)
| | | | +- setuptools(install version:42.0.2 version range:>0.6)
| | | | +- six(install version:1.13.0 version range:*)
| | | +- netaddr(install version:0.7.19 version range:*)
| | | +- paramiko(install version:2.7.1 version range:>=1.15.2)
| | | +- pyserial(install version:3.4 version range:*)
| | | +- pyyaml(install version:5.2 version range:>=5.1)
| | | +- scp(install version:0.13.2 version range:>=0.7.0)
| | | | +- paramiko(install version:2.7.1 version range:*)
| | | +- six(install version:1.13.0 version range:*)
| | +- netaddr(install version:0.7.19 version range:*)
| | +- netmiko(install version:2.4.2 version range:==2.4.2)
| | | +- enum34(install version:1.1.6 version range:*)
| | | +- ipaddress(install version:1.0.23 version range:*)
| | | +- paramiko(install version:2.7.1 version range:>=2.4.3)
| | | +- pyserial(install version:3.4 version range:*)
| | | +- scp(install version:0.13.2 version range:>=0.13.2)
| | | | +- paramiko(install version:2.7.1 version range:*)
| | | +- setuptools(install version:42.0.2 version range:>=38.4.0)
| | | +- textfsm(install version:1.1.0 version range:*)
| | | | +- future(install version:0.18.2 version range:*)
| | | | +- six(install version:1.13.0 version range:*)
| | +- nxapi-plumbing(install version:0.5.2 version range:>=0.5.2)
| | | +- future(install version:0.18.2 version range:*)
| | | +- lxml(install version:4.4.2 version range:*)
| | | +- requests(install version:2.22.0 version range:>=2.7.0)
| | | | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| | | +- scp(install version:0.13.2 version range:*)
| | | | +- paramiko(install version:2.7.1 version range:*)
| | | +- six(install version:1.13.0 version range:*)
| | +- paramiko(install version:2.7.1 version range:>=2.4.2)
| | +- pyeapi(install version:0.8.2 version range:>=0.8.2)
| | | +- netaddr(install version:0.7.19 version range:*)
| | +- pyIOSXR(install version:0.53 version range:>=0.53)
| | | +- lxml(install version:4.4.2 version range:>=3.2.4)
| | | +- netmiko(install version:2.4.2 version range:>=1.4.3)
| | | | +- enum34(install version:1.1.6 version range:*)
| | | | +- ipaddress(install version:1.0.23 version range:*)
| | | | +- paramiko(install version:2.7.1 version range:>=2.4.3)
| | | | +- pyserial(install version:3.4 version range:*)
| | | | +- scp(install version:0.13.2 version range:>=0.13.2)
| | | | +- setuptools(install version:42.0.2 version range:>=38.4.0)
| | | | +- textfsm(install version:1.1.0 version range:*)
| | +- pyYAML(install version:5.2 version range:*)
| | +- scp(install version:0.13.2 version range:*)
| | | +- paramiko(install version:2.7.1 version range:*)
| | +- setuptools(install version:42.0.2 version range:>=38.4.0)
| | +- textfsm(install version:1.1.0 version range:*)
| | | +- future(install version:0.18.2 version range:*)
| | | +- six(install version:1.13.0 version range:*)
| +- ncclient(install version:0.6.6 version range:>=0.6.6,<0.7.0)
| | +- lxml(install version:4.4.2 version range:>=3.3.0)
| | +- paramiko(install version:2.7.1 version range:>=1.15.0)
| | +- selectors2(install version:2.0.1 version range:>=2.0.1)
| | +- setuptools(install version:42.0.2 version range:>0.6)
| | +- six(install version:1.13.0 version range:*)
| +- netmiko(install version:2.4.2 version range:>=2.3.3,<3.0.0)
| | +- enum34(install version:1.1.6 version range:*)
| | +- ipaddress(install version:1.0.23 version range:*)
| | +- paramiko(install version:2.7.1 version range:>=2.4.3)
| | +- pyserial(install version:3.4 version range:*)
| | +- scp(install version:0.13.2 version range:>=0.13.2)
| | | +- paramiko(install version:2.7.1 version range:*)
| | +- setuptools(install version:42.0.2 version range:>=38.4.0)
| | +- textfsm(install version:1.1.0 version range:*)
| | | +- future(install version:0.18.2 version range:*)
| | | +- six(install version:1.13.0 version range:*)
| +- paramiko(install version:2.7.1 version range:>=2.1.1,<3.0.0)
| +- pydantic(install version:0.18.2 version range:>=0.18.2,<0.19.0)
| | +- dataclasses(install version:0.7 version range:>=0.6)
| +- requests(install version:2.22.0 version range:>=2,<3)
| | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- ruamel.yaml(install version:0.15.100 version range:>=0.15.85,<0.16.0)
| +- typing_extensions(install version:3.7.4.1 version range:>=3.7,<4.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment] 2019-12-11 14:12
### Suggested Solution

1.	Ask your upstream project napalmto loose the version range of _**junos-eznc**_.
2.	Remove your direct dependency **_junos-eznc_**, and use **_junos-eznc_** transitively introduced by **_napalm_**.

@dbarrosop Which solution do you prefer, 1 or 2?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by ktbyers** [comment] 2019-12-11 18:01
I think we should do 2 i.e. remove the direct dependency on `junos-eznc` and pull it in via NAPALM.

The other option is to pin the direct dependency to 2.2.1.

The cause was a change that PyEZ library made that broke napalm tests--it is only a testing issue and not a real issue (i.e. we mocked a PyEZ connection and are now missing a needed attribute in napalm).

The issue will be fixed in the next NAPALM release. Though we will have to roll Nornir pyproject.toml for that anyways as it will be NAPALM 3.X.X.

**Comment by dmfigol** [comment] 2019-12-11 20:00
if we don't directly use `junos-eznc`, then it should not be in our direct dependency list.
I agree with @ktbyers

**Comment by dbarrosop** [comment] 2019-12-11 21:26
Thanks a lot for reporting the issue and for the extensr analysis and proposed solutions. I concur with Kirk and Dimitri, I think removing the direct dependency is the best solution.

**Comment by NeolithEra** [comment] 2019-12-13 11:04
@dbarrosop @dmfigol @ktbyers, Thanks for your quick feedback. I will submit a PR to solve this problem. :-P

**Closed** 2020-01-14 07:59 UTC
