### ISSUE TITLE
Cisco Genie processing fails when inventory uses >1 worker using Nornir 2.20

### ISSUE THREAD

**Issue by jesse-mcgraw** [nornir-automation/nornir#440] opened 2019-10-07 17:17 UTC
At the moment I'm not sure if this is an issue with my code, Nornir or perhaps even Genie.

With an inventory that consists of multiple hosts, when running a sub-task that uses Genie to parse "show version" output, Genie will fail to parse if I initialize the inventory with a number of workers > 1 (for instance using "core={"num_workers": 2}")

If I use 1 worker then everything works as expected.

Any ideas on where I could start looking?

**Comment by dmfigol** [comment] 2019-10-07 17:19
Please start by sharing your code and the traceback message.

**Comment by ktbyers** [comment] 2019-10-07 17:23
FYI, we were able to reproduce this. And Genie documentation states they don't support threading.

The solution/workaround we used was:

1. Gather information using Netmiko and save in the program (or in a file).
2. Set number of workers to 1 and process the output with Genie in a single threaded way. Since this is entirely local at this point, it will execute very rapidly.


It is not a Nornir/Netmiko issue, but is a Genie library issue.

We should probably close this here.

**Comment by jesse-mcgraw** [comment] 2019-10-07 17:23
There's no traceback, it just doesn't parse the CLI output to a dict like it typically does.

Generally speaking, the code looks like this:


```
result = device_nornir.run(task=check_ntp_as_task)


def check_ntp_as_task(task: Task):
	# Get "show version"
	result = task.run(task=get_show_version)
	
	
def get_show_version(task: Task):
    
	""" show version """
    print_title(f"{task.name}")

    try:
        result = task.run(task=netmiko_send_command, command_string=f"show version", use_genie=True)
        print_result(result)
        show_version = result[0].result
    except Exception as e:
        task.host["failed"] = True
        print(f"Exception: {e}")
        raise NornirSubTaskError(task, result)
```

**Comment by ktbyers** [comment] 2019-10-07 17:25
We should probably move the solution/workaround for this to https://nornir.discourse.group/ as this will come up again.

@jesse-mcgraw if you re-ask this question in Nornir-Discourse, we will try to answer there and see if we can post an example of the workaround.

**Comment by jesse-mcgraw** [comment] 2019-10-07 17:26
Thanks @ktbyers, I'll close this issue

**Comment by jesse-mcgraw** [comment] 2019-10-07 17:33
Discourse discussion thread started here: https://nornir.discourse.group/t/cisco-genie-fails-to-parse-output-when-using-1-inventory-worker/172

**Comment by jesse-mcgraw** [comment] 2019-10-07 18:44
Re-opening as a Genie developer is involved in the discourse thread and is also curious as to why this isn't working as expected.

**Comment by ktbyers** [comment] 2019-10-07 19:09
Sounds good. Working on reproducing the behavior I saw earlier.

**Comment by ktbyers** [comment] 2019-10-07 19:28
My test code is here:

```pythong
from nornir import InitNornir
from nornir.core.filter import F
from nornir.plugins.tasks.networking import netmiko_send_command

from netmiko.utilities import get_structured_data_genie

DEBUG = False


def run_netmiko(task, cmd):
    multi_result = task.run(task=netmiko_send_command, command_string=cmd, use_genie=True)
    output = multi_result[0].result
    print(f"Host: {task.host}")
    print("-" * 40)
    print(output)
    print("-" * 40)
    print()
    host = task.host
    host[cmd] = output


if __name__ == "__main__":
    nr = InitNornir(config_file="config.yaml")
    ios_filter = F(groups__contains="ios")
    nr = nr.filter(ios_filter)
    cmd = "show ip interface brief"
    result = nr.run(task=run_netmiko, num_workers=10, cmd=cmd)
```

Executing against 2 x Cisco IOS devices and 2 Cisco IOS-XE devices.

The general pattern is some devices will fail the parsing.

**Comment by ktbyers** [comment] 2019-10-07 19:29
Example output:

```$ python genie_simple.py 
Host: cisco3
----------------------------------------
{'interface': {'GigabitEthernet0/0/0': {'ip_address': '10.220.88.22', 'interface_is_ok': 'YES', 'method': 'NVRAM', 'status': 'up', 'protocol': 'up'}, 'GigabitEthernet0/0/1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'NVRAM', 'status': 'administratively down', 'protocol': 'down'}, 'GigabitEthernet0/1/0': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'GigabitEthernet0/1/1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'GigabitEthernet0/1/2': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'GigabitEthernet0/1/3': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'Vlan1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'up', 'protocol': 'down'}}}
----------------------------------------

Host: cisco4
----------------------------------------
{'interface': {'GigabitEthernet0/0/0': {'ip_address': '10.220.88.23', 'interface_is_ok': 'YES', 'method': 'NVRAM', 'status': 'up', 'protocol': 'up'}, 'GigabitEthernet0/0/1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'administratively down', 'protocol': 'down'}, 'GigabitEthernet0/1/0': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'GigabitEthernet0/1/1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'GigabitEthernet0/1/2': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'GigabitEthernet0/1/3': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'Vlan1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'up', 'protocol': 'down'}}}
----------------------------------------

Host: cisco1
----------------------------------------
{'interface': {'FastEthernet0': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet2': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet3': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet4': {'ip_address': '10.220.88.20', 'interface_is_ok': 'YES', 'method': 'NVRAM', 'status': 'up', 'protocol': 'up'}, 'Vlan1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}}}
----------------------------------------

Host: cisco2
----------------------------------------
{'interface': {'FastEthernet0': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet2': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet3': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}, 'FastEthernet4': {'ip_address': '10.220.88.21', 'interface_is_ok': 'YES', 'method': 'NVRAM', 'status': 'up', 'protocol': 'up'}, 'Vlan1': {'ip_address': 'unassigned', 'interface_is_ok': 'YES', 'method': 'unset', 'status': 'down', 'protocol': 'down'}}}
----------------------------------------

```

**Comment by ktbyers** [comment] 2019-10-07 19:31
Which device(s) fail the parsing will vary.

```
$ pip list | grep pyats
pyats                        19.9.2      
pyats.aereport               19.9        
pyats.aetest                 19.9.1      
pyats.async                  19.9        
pyats.connections            19.9        
pyats.datastructures         19.9        
pyats.easypy                 19.9.3      
pyats.kleenex                19.9.1      
pyats.log                    19.9.1      
pyats.reporter               19.9.1      
pyats.results                19.9        
pyats.tcl                    19.9        
pyats.topology               19.9        
pyats.utils                  19.9        

(py3_genie) [kbyers@norn1a genie_threads]$ pip list | grep genie
genie                        19.9        
genie.abstract               19.9        
genie.conf                   19.9        
genie.harness                19.9        
genie.libs.conf              19.9        
genie.libs.filetransferutils 19.9        
genie.libs.ops               19.9        
genie.libs.parser            19.9        
genie.libs.sdk               19.9.1      
genie.libs.telemetry         19.9        
genie.metaparser             19.9        
genie.ops                    19.9        
genie.parsergen              19.9        
genie.predcore               19.9        
genie.telemetry              19.9        
genie.trafficgen             19.9        
genie.utils                  19.9        

(py3_genie) [kbyers@norn1a genie_threads]$ pip list | grep nornir
nornir                       2.3.0       

(py3_genie) [kbyers@norn1a genie_threads]$ pip list | grep netmiko
netmiko                      2.4.2  
```

**Comment by ktbyers** [comment] 2019-10-07 19:35
Netmiko has an exception handler which causes it to fallback to the raw_output if Genie fails. Digging into that exception handler some more. Here is the Genie exception that happens:

```
ipdb> e                                                                                                                                   
LookupError("No such attribute in abstraction package 'genie.libs.parser': 'genie.libs.parser.show_interface'",)
```

**Comment by ktbyers** [comment] 2019-10-07 19:41
Here is the Netmiko code that is calling the Genie library:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/utilities.py#L262

**Comment by ktbyers** [comment] 2019-10-07 19:43
Note, I switched to the Netmiko `develop` branch so I could modify the exception handling (to get more details on the underlying Genie library exception), but I don't think that changed the behavior with respect to Genie-library.

**Comment by ktbyers** [comment] 2019-10-07 19:46
If I change num_workers to be 1 (i.e. disable multi-threading), it works without any errors (albeit slower):

```python
 result = nr.run(task=run_netmiko, num_workers=1, cmd=cmd)
```

**Comment by jeaubin** [comment] 2019-10-08 13:28
Thanks for the detailed steps,  we will look into what could be the problem.

**Comment by jesse-mcgraw** [comment] 2019-10-08 21:33
A related issue opened in Netmiko: https://github.com/ktbyers/netmiko/issues/1347

**Comment by jesse-mcgraw** [comment] 2019-10-09 12:21
Is the majority of the functionality of Nornir built on using threads vs. using processes? 

I assume that switching to using processes is not just a simple matter of using "from multiprocessing import Pool" vs. "from multiprocessing.dummy import Pool"

**Comment by dmfigol** [comment] 2019-10-09 12:25
Nornir is using threads because it is much more efficient for i/o bound operations like communication with the network devices.

**Comment by ktbyers** [comment] 2019-10-09 16:21
If it is simple...this might be a worthwhile PR i.e. environment variable and configuration option to control whether threads/processes are used.

**Comment by dmfigol** [comment] 2019-10-09 16:23
What would be the use-case for using multiple processes though?

**Comment by ktbyers** [comment] 2019-10-09 16:38
One use case is a situation where threading breaks...like in this Genie case. 

Also if you have workloads that have some CPU-heavy part to them...then the GIL would be an issue. So then multiprocessing would probably make sense.

Also if you are only running 20 workers threading/multiprocessing probably doesn't matter at all from a system load perspective (i.e. the system cost of the additional processes rounds to zero).

**Comment by dmfigol** [comment] 2019-10-09 16:41
I disagree almost on all listed points but probably this issue is not the right place to discuss multiprocessing in nornir.

**Comment by jesse-mcgraw** [comment] 2019-10-09 16:42
@ktbyers Just to be clear, I wasn't say that the thread/process switch would be simple, more just that the cause is probably well understood.

I did try a quick experiment with using processes by using "import multiprocess as pool" and it would crash on __getattr__ in the MultiResult class.  Commenting it out would let it proceed further but not completely succeed.  

Unfortunately,I am not enough of a python guru to dig deeper than that yet

**Comment by ktbyers** [comment] 2019-10-09 16:50
@dmfigol Okay...why?

**Comment by ktbyers** [comment] 2019-10-09 17:10
If it is not very simple...then not worth doing (at least to me). 

And from the above...probably should have a separate GitHub issue if discussion on multiprocessing continues.

**Comment by ogenstad** [comment] 2019-10-09 17:57
What problem is it we are trying to solve here? I think it's quite clear that this is an issue on the Genie side. As far as I know it's only a library to parse text and as such it shouldn't care about threads in any way.

A current workaround in Nornir would be to run a task with multiple workers to collect the data and then have another task with num_workers=1 that parses the information using Genie.

**Comment by simingy** [comment] 2019-10-10 03:46
@ogenstad parsing libraries is about a single digit % of what Genie libs provides, but it seems to be the only thing people understand right now, though this is really not a place where this should be discussed.

our abstraction library loading layer didn't like thread (we're a multi-process fab). Though, that's been fixed. The fix will propagate your way soon.

Thank you @jesse-mcgraw for bringing this to attention.

**Comment by ktbyers** [comment] 2019-10-10 03:52
Thanks @simingy. Do you know what Genie/PyATS release this will be fixed in?

**Comment by simingy** [comment] 2019-10-10 03:55
i think we'll give @jesse-mcgraw a beta pkg, and release the fix in v19.10 officially (last tuesday of oct 2019)

**Comment by ktbyers** [comment] 2019-10-10 05:40
@simingy Sounds good. Thanks

**Comment by dmfigol** [comment] 2019-10-10 13:24
Thanks @simingy for addressing this so quickly.
I will proceed with the closure of this issue.

**Closed by dmfigol** 2019-10-10 13:24 UTC

**Comment by jeaubin** [comment] 2019-10-10 15:05
After fix; 

![image](https://user-images.githubusercontent.com/576771/66581260-cf091980-eb4d-11e9-90b3-f764a296b5fb.png)

**Comment by jesse-mcgraw** [comment] 2019-10-30 19:36
This appears to have been resolved by the 19.9 Genie release, at least in my limited testing.

**Comment by ktbyers** [comment] 2019-10-30 19:58
@jesse-mcgraw I assume you meant `19.10` release?

**Comment by jesse-mcgraw** [comment] 2019-10-30 22:16
Sheesh.  Yes, that's what I meant.
